[package]
name = "ggst-api"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11" }
tokio = { version = "1", features = ["full"] }
chrono = { package = "chrono", version = "0.4" }
derivative = "2"
rmp-serde = "1"
serde_crate = { package = "serde", version = "1.0", features = ["derive"] }
serde_json = "1"
bytes = "1"
aes-gcm = "*"
base64-url = "1.4.13"
hex = "0.4.3"
cipher = "0.4"
rand = "0.8.5"

[dev-dependencies]
expect-test = "1"
rmpv = { version = "1", features = ["with-serde"] }
serde_path_to_error = "0.1"

[features]
serde = ["chrono/serde"]